/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchRouteImport } from './routes/watch'
import { Route as TokenRouteImport } from './routes/token'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StreamOverlayRouteImport } from './routes/stream-overlay'
import { Route as StoryRouteImport } from './routes/story'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PvpRouteImport } from './routes/pvp'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as DuelRouteImport } from './routes/duel'
import { Route as DiscordCallbackRouteImport } from './routes/discord-callback'
import { Route as DecksRouteImport } from './routes/decks'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as CliquesRouteImport } from './routes/cliques'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as AgentDevRouteImport } from './routes/agent-dev'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoryChapterIdRouteImport } from './routes/story.$chapterId'
import { Route as PlayMatchIdRouteImport } from './routes/play.$matchId'
import { Route as DecksDeckIdRouteImport } from './routes/decks.$deckId'
import { Route as CardsCardIdRouteImport } from './routes/cards.$cardId'

const WatchRoute = WatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenRoute = TokenRouteImport.update({
  id: '/token',
  path: '/token',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamOverlayRoute = StreamOverlayRouteImport.update({
  id: '/stream-overlay',
  path: '/stream-overlay',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PvpRoute = PvpRouteImport.update({
  id: '/pvp',
  path: '/pvp',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DuelRoute = DuelRouteImport.update({
  id: '/duel',
  path: '/duel',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscordCallbackRoute = DiscordCallbackRouteImport.update({
  id: '/discord-callback',
  path: '/discord-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksRoute = DecksRouteImport.update({
  id: '/decks',
  path: '/decks',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const CliquesRoute = CliquesRouteImport.update({
  id: '/cliques',
  path: '/cliques',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentDevRoute = AgentDevRouteImport.update({
  id: '/agent-dev',
  path: '/agent-dev',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryChapterIdRoute = StoryChapterIdRouteImport.update({
  id: '/$chapterId',
  path: '/$chapterId',
  getParentRoute: () => StoryRoute,
} as any)
const PlayMatchIdRoute = PlayMatchIdRouteImport.update({
  id: '/play/$matchId',
  path: '/play/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksDeckIdRoute = DecksDeckIdRouteImport.update({
  id: '/$deckId',
  path: '/$deckId',
  getParentRoute: () => DecksRoute,
} as any)
const CardsCardIdRoute = CardsCardIdRouteImport.update({
  id: '/$cardId',
  path: '/$cardId',
  getParentRoute: () => CardsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agent-dev': typeof AgentDevRoute
  '/cards': typeof CardsRouteWithChildren
  '/cliques': typeof CliquesRoute
  '/collection': typeof CollectionRoute
  '/decks': typeof DecksRouteWithChildren
  '/discord-callback': typeof DiscordCallbackRoute
  '/duel': typeof DuelRoute
  '/leaderboard': typeof LeaderboardRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/pvp': typeof PvpRoute
  '/settings': typeof SettingsRoute
  '/story': typeof StoryRouteWithChildren
  '/stream-overlay': typeof StreamOverlayRoute
  '/terms': typeof TermsRoute
  '/token': typeof TokenRoute
  '/watch': typeof WatchRoute
  '/cards/$cardId': typeof CardsCardIdRoute
  '/decks/$deckId': typeof DecksDeckIdRoute
  '/play/$matchId': typeof PlayMatchIdRoute
  '/story/$chapterId': typeof StoryChapterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agent-dev': typeof AgentDevRoute
  '/cards': typeof CardsRouteWithChildren
  '/cliques': typeof CliquesRoute
  '/collection': typeof CollectionRoute
  '/decks': typeof DecksRouteWithChildren
  '/discord-callback': typeof DiscordCallbackRoute
  '/duel': typeof DuelRoute
  '/leaderboard': typeof LeaderboardRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/pvp': typeof PvpRoute
  '/settings': typeof SettingsRoute
  '/story': typeof StoryRouteWithChildren
  '/stream-overlay': typeof StreamOverlayRoute
  '/terms': typeof TermsRoute
  '/token': typeof TokenRoute
  '/watch': typeof WatchRoute
  '/cards/$cardId': typeof CardsCardIdRoute
  '/decks/$deckId': typeof DecksDeckIdRoute
  '/play/$matchId': typeof PlayMatchIdRoute
  '/story/$chapterId': typeof StoryChapterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agent-dev': typeof AgentDevRoute
  '/cards': typeof CardsRouteWithChildren
  '/cliques': typeof CliquesRoute
  '/collection': typeof CollectionRoute
  '/decks': typeof DecksRouteWithChildren
  '/discord-callback': typeof DiscordCallbackRoute
  '/duel': typeof DuelRoute
  '/leaderboard': typeof LeaderboardRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/pvp': typeof PvpRoute
  '/settings': typeof SettingsRoute
  '/story': typeof StoryRouteWithChildren
  '/stream-overlay': typeof StreamOverlayRoute
  '/terms': typeof TermsRoute
  '/token': typeof TokenRoute
  '/watch': typeof WatchRoute
  '/cards/$cardId': typeof CardsCardIdRoute
  '/decks/$deckId': typeof DecksDeckIdRoute
  '/play/$matchId': typeof PlayMatchIdRoute
  '/story/$chapterId': typeof StoryChapterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/agent-dev'
    | '/cards'
    | '/cliques'
    | '/collection'
    | '/decks'
    | '/discord-callback'
    | '/duel'
    | '/leaderboard'
    | '/onboarding'
    | '/privacy'
    | '/profile'
    | '/pvp'
    | '/settings'
    | '/story'
    | '/stream-overlay'
    | '/terms'
    | '/token'
    | '/watch'
    | '/cards/$cardId'
    | '/decks/$deckId'
    | '/play/$matchId'
    | '/story/$chapterId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/agent-dev'
    | '/cards'
    | '/cliques'
    | '/collection'
    | '/decks'
    | '/discord-callback'
    | '/duel'
    | '/leaderboard'
    | '/onboarding'
    | '/privacy'
    | '/profile'
    | '/pvp'
    | '/settings'
    | '/story'
    | '/stream-overlay'
    | '/terms'
    | '/token'
    | '/watch'
    | '/cards/$cardId'
    | '/decks/$deckId'
    | '/play/$matchId'
    | '/story/$chapterId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/agent-dev'
    | '/cards'
    | '/cliques'
    | '/collection'
    | '/decks'
    | '/discord-callback'
    | '/duel'
    | '/leaderboard'
    | '/onboarding'
    | '/privacy'
    | '/profile'
    | '/pvp'
    | '/settings'
    | '/story'
    | '/stream-overlay'
    | '/terms'
    | '/token'
    | '/watch'
    | '/cards/$cardId'
    | '/decks/$deckId'
    | '/play/$matchId'
    | '/story/$chapterId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AgentDevRoute: typeof AgentDevRoute
  CardsRoute: typeof CardsRouteWithChildren
  CliquesRoute: typeof CliquesRoute
  CollectionRoute: typeof CollectionRoute
  DecksRoute: typeof DecksRouteWithChildren
  DiscordCallbackRoute: typeof DiscordCallbackRoute
  DuelRoute: typeof DuelRoute
  LeaderboardRoute: typeof LeaderboardRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  PvpRoute: typeof PvpRoute
  SettingsRoute: typeof SettingsRoute
  StoryRoute: typeof StoryRouteWithChildren
  StreamOverlayRoute: typeof StreamOverlayRoute
  TermsRoute: typeof TermsRoute
  TokenRoute: typeof TokenRoute
  WatchRoute: typeof WatchRoute
  PlayMatchIdRoute: typeof PlayMatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token': {
      id: '/token'
      path: '/token'
      fullPath: '/token'
      preLoaderRoute: typeof TokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stream-overlay': {
      id: '/stream-overlay'
      path: '/stream-overlay'
      fullPath: '/stream-overlay'
      preLoaderRoute: typeof StreamOverlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pvp': {
      id: '/pvp'
      path: '/pvp'
      fullPath: '/pvp'
      preLoaderRoute: typeof PvpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duel': {
      id: '/duel'
      path: '/duel'
      fullPath: '/duel'
      preLoaderRoute: typeof DuelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discord-callback': {
      id: '/discord-callback'
      path: '/discord-callback'
      fullPath: '/discord-callback'
      preLoaderRoute: typeof DiscordCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks': {
      id: '/decks'
      path: '/decks'
      fullPath: '/decks'
      preLoaderRoute: typeof DecksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliques': {
      id: '/cliques'
      path: '/cliques'
      fullPath: '/cliques'
      preLoaderRoute: typeof CliquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-dev': {
      id: '/agent-dev'
      path: '/agent-dev'
      fullPath: '/agent-dev'
      preLoaderRoute: typeof AgentDevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story/$chapterId': {
      id: '/story/$chapterId'
      path: '/$chapterId'
      fullPath: '/story/$chapterId'
      preLoaderRoute: typeof StoryChapterIdRouteImport
      parentRoute: typeof StoryRoute
    }
    '/play/$matchId': {
      id: '/play/$matchId'
      path: '/play/$matchId'
      fullPath: '/play/$matchId'
      preLoaderRoute: typeof PlayMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/$deckId': {
      id: '/decks/$deckId'
      path: '/$deckId'
      fullPath: '/decks/$deckId'
      preLoaderRoute: typeof DecksDeckIdRouteImport
      parentRoute: typeof DecksRoute
    }
    '/cards/$cardId': {
      id: '/cards/$cardId'
      path: '/$cardId'
      fullPath: '/cards/$cardId'
      preLoaderRoute: typeof CardsCardIdRouteImport
      parentRoute: typeof CardsRoute
    }
  }
}

interface CardsRouteChildren {
  CardsCardIdRoute: typeof CardsCardIdRoute
}

const CardsRouteChildren: CardsRouteChildren = {
  CardsCardIdRoute: CardsCardIdRoute,
}

const CardsRouteWithChildren = CardsRoute._addFileChildren(CardsRouteChildren)

interface DecksRouteChildren {
  DecksDeckIdRoute: typeof DecksDeckIdRoute
}

const DecksRouteChildren: DecksRouteChildren = {
  DecksDeckIdRoute: DecksDeckIdRoute,
}

const DecksRouteWithChildren = DecksRoute._addFileChildren(DecksRouteChildren)

interface StoryRouteChildren {
  StoryChapterIdRoute: typeof StoryChapterIdRoute
}

const StoryRouteChildren: StoryRouteChildren = {
  StoryChapterIdRoute: StoryChapterIdRoute,
}

const StoryRouteWithChildren = StoryRoute._addFileChildren(StoryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AgentDevRoute: AgentDevRoute,
  CardsRoute: CardsRouteWithChildren,
  CliquesRoute: CliquesRoute,
  CollectionRoute: CollectionRoute,
  DecksRoute: DecksRouteWithChildren,
  DiscordCallbackRoute: DiscordCallbackRoute,
  DuelRoute: DuelRoute,
  LeaderboardRoute: LeaderboardRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  PvpRoute: PvpRoute,
  SettingsRoute: SettingsRoute,
  StoryRoute: StoryRouteWithChildren,
  StreamOverlayRoute: StreamOverlayRoute,
  TermsRoute: TermsRoute,
  TokenRoute: TokenRoute,
  WatchRoute: WatchRoute,
  PlayMatchIdRoute: PlayMatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
