import { buildWorldCreationKit } from "./generatorAssets";
import type { PlayableWorld } from "./types";

export const playableWorlds: PlayableWorld[] = [
  {
    id: "neon-borough",
    name: "Neon Borough: Vice Circuit",
    tagline: "Corporate gods, street saints, and one bad night.",
    genre: "Cyberpunk urban fantasy",
    mood: "Fast, stylish, conspiratorial",
    recommendedPartySize: "3-5 players",
    sessionLength: "75-120 min",
    viralityHooks: [
      "Every session ends with a clip-ready reveal scene.",
      "Player-designed crews can be published as reusable templates.",
      "Weekly district reset creates shared live-event urgency.",
    ],
    rules: {
      id: "pulse-d20",
      name: "Pulse d20",
      summary: "Roll 1d20 + stat + edge die against DC. Fails create Heat, not dead ends.",
      turnLoop: ["Scout", "Position", "Execute", "Aftershock"],
      failForwardPolicy: "On fail, action succeeds with consequence or escalating Heat.",
      escalationTrack: "Heat 0-6 unlocks district response tiers.",
    },
    diceMoves: [
      {
        id: "action-check",
        label: "Action Check",
        expression: "1d20 + stat + 1d6(edge)",
        successRule: "Meet or beat DC.",
        failRule: "Gain Heat +1 and trigger a complication.",
      },
      {
        id: "social-breach",
        label: "Social Breach",
        expression: "2d10 + presence",
        successRule: "15+ gains leverage tag.",
        failRule: "Target gains suspicion tag.",
      },
      {
        id: "firefight",
        label: "Firefight",
        expression: "1d20 + grit",
        successRule: "Hit deals weapon tier damage.",
        failRule: "Suppressive fire pins the acting unit.",
      },
    ],
    archetypes: [
      {
        id: "circuit-runner",
        title: "Circuit Runner",
        fantasy: "Outrun drones, reroute systems, vanish through service tunnels.",
        stats: [
          { key: "grit", label: "Grit", min: 0, max: 5, base: 2 },
          { key: "edge", label: "Edge", min: 0, max: 5, base: 4 },
          { key: "presence", label: "Presence", min: 0, max: 5, base: 1 },
        ],
        startingMoves: ["Ghost Route", "Pulse Skip", "Backdoor Cache"],
        startingGear: ["Kinetic skates", "EMP laces", "Signal veil"],
        generationPromptSeed: "High-speed infiltrator who solves with movement first.",
      },
      {
        id: "choir-hacker",
        title: "Choir Hacker",
        fantasy: "Break corporate liturgy and rewrite machine prayers.",
        stats: [
          { key: "grit", label: "Grit", min: 0, max: 5, base: 1 },
          { key: "edge", label: "Edge", min: 0, max: 5, base: 3 },
          { key: "presence", label: "Presence", min: 0, max: 5, base: 3 },
        ],
        startingMoves: ["Zero-Day Hymn", "Blackout Liturgy", "Echo Scramble"],
        startingGear: ["Shard deck", "Optic halo", "Trace blockers"],
        generationPromptSeed: "Aggressive systems intruder with ritualized code language.",
      },
      {
        id: "street-paladin",
        title: "Street Paladin",
        fantasy: "Frontline protector with neighborhood loyalty network.",
        stats: [
          { key: "grit", label: "Grit", min: 0, max: 5, base: 4 },
          { key: "edge", label: "Edge", min: 0, max: 5, base: 1 },
          { key: "presence", label: "Presence", min: 0, max: 5, base: 2 },
        ],
        startingMoves: ["Stand Ground", "Shield Bloom", "Community Call"],
        startingGear: ["Rail buckler", "Pulse baton", "Med foam"],
        generationPromptSeed: "Defender with tactical positioning and social trust.",
      },
    ],
    hostedAgents: [
      {
        id: "gm-milaidy-node",
        role: "gm",
        name: "Milaidy Node",
        voice: "Cool, clipped, witty",
        personality: ["streetwise", "cinematic", "dangerously curious"],
        directives: [
          "Push toward difficult choices, not binary success/failure.",
          "Always offer one creative non-combat solve.",
          "End each episode with a social-share worthy sting.",
        ],
      },
      {
        id: "npc-fixer",
        role: "npc",
        name: "Patchwork Cinder",
        voice: "Fast-talking broker",
        personality: ["mercenary", "funny", "paranoid"],
        directives: ["Trade in favors", "Expose faction conflicts", "Escalate stakes every 20 minutes"],
      },
    ],
    playerAgentTemplates: [
      {
        id: "agent-rush",
        role: "player",
        name: "Rushline",
        voice: "Young and sharp",
        personality: ["reckless", "optimistic", "loyal"],
        directives: ["Take first opening", "Protect civilians", "Escalate style over stealth"],
      },
      {
        id: "agent-latch",
        role: "player",
        name: "Latch",
        voice: "Measured and dry",
        personality: ["analytical", "quiet", "suspicious"],
        directives: ["Map exits", "Control tempo", "Call out trap risk"],
      },
    ],
    maps: [
      {
        id: "chrome-bazaar",
        name: "Chrome Bazaar",
        biome: "Night market over rain-slick alleys",
        camera: "isometric",
        lightingPreset: "Neon bloom + dynamic shadow lanes",
        ambience: ["vendor chatter", "electric hum", "distant sirens"],
        objectives: ["Secure package", "Identify mole", "Escape through tram roof"],
      },
      {
        id: "subway-catacombs",
        name: "Subway Catacombs",
        biome: "Abandoned maglev tunnels",
        camera: "topdown",
        lightingPreset: "Emergency red strips + flicker pulses",
        ambience: ["dripping water", "old rail grind", "signal crackle"],
        objectives: ["Disable relay", "Evade hunter drones", "Find dead drop vault"],
      },
      {
        id: "cloudline-spire",
        name: "Cloudline Spire",
        biome: "Corporate tower with skybridges",
        camera: "cinematic",
        lightingPreset: "Cold white interior + billboard glare",
        ambience: ["HVAC roar", "PA announcements", "glass resonance"],
        objectives: ["Extract witness", "Plant ledger worm", "Broadcast truth packet"],
      },
    ],
    dungeons: [
      {
        id: "district-nine-vault",
        name: "District Nine Vault",
        objective: "Steal proof of synthetic election rigging.",
        rooms: [
          {
            id: "security-funnel",
            name: "Security Funnel",
            challenge: "Two overlapping camera cones and rotating sentry team.",
            checks: ["Action Check DC 14", "Social Breach DC 16"],
            failForward: "Alarm trips but false floor map is leaked.",
            rewards: ["Access card alpha", "Favorable route to archive"],
          },
          {
            id: "cold-archive",
            name: "Cold Archive",
            challenge: "Data shards protected by legal language traps.",
            checks: ["Action Check DC 15", "Firefight DC 13 if ambushed"],
            failForward: "You grab incomplete files with planted disinformation.",
            rewards: ["Evidence fragment", "Corporate ledger key"],
          },
          {
            id: "liftwell-gauntlet",
            name: "Liftwell Gauntlet",
            challenge: "Vertical chase under suppressive fire.",
            checks: ["Firefight DC 15", "Action Check DC 12"],
            failForward: "Team escapes but leaves biometric trace.",
            rewards: ["Broadcast node access", "Faction reputation boost"],
          },
        ],
      },
    ],
    campaign: [
      {
        id: "arc-ghost-index",
        title: "Ghost Index",
        levelRange: "1-4",
        beats: [
          {
            id: "beat-1",
            title: "The Missing Courier",
            objective: "Find the courier before corp cleanup does.",
            successOutcome: "Courier reveals vault coordinates.",
            failForward: "Courier dies, leaving fragmented AI memory shard.",
            gmPrompt: "Frame every clue as a tradeoff between speed and stealth.",
          },
          {
            id: "beat-2",
            title: "Bazaar Blackout",
            objective: "Protect neighborhood grid during rolling blackout raid.",
            successOutcome: "District allies unlock hidden route network.",
            failForward: "Power returns under faction control; taxes rise.",
            gmPrompt: "Force split-second decisions between mission and civilians.",
          },
          {
            id: "beat-3",
            title: "Spire Broadcast",
            objective: "Air the evidence before election lock.",
            successOutcome: "Public unrest creates new campaign season.",
            failForward: "Evidence airs late; target gains legal immunity.",
            gmPrompt: "End with a visual cliffhanger for social clips.",
          },
        ],
      },
    ],
    creationKit: buildWorldCreationKit({
      worldName: "Neon Borough: Vice Circuit",
      genre: "Cyberpunk urban fantasy",
      mood: "Fast, stylish, conspiratorial",
      uniqueConstraint: "Every fail escalates district Heat and changes patrol graph.",
      assetManifest: {
        tilesets: ["Neon Alley Pack", "Corporate Atrium", "Transit Tunnel Kit"],
        minis: ["Street Crew Set", "Corp Security Squad", "Drone Swarm A/B"],
        props: ["Holo kiosks", "Signal relays", "Rooftop vents"],
        music: ["neon-nocturne.ogg", "chase-grid.ogg", "last-broadcast.ogg"],
        sfx: ["sirens.wav", "terminal-hack.wav", "zipline.wav"],
      },
      sessionZeroChecklist: [
        "Set acceptable PvP and betrayal boundaries.",
        "Pick district allegiance for each player.",
        "Define one shared crew debt.",
      ],
      playtestMatrix: [
        {
          scenario: "Stealth-first vault run",
          expectedOutcome: "At least one route survives after alarm.",
          passCondition: "No scene hard-locks progression.",
        },
        {
          scenario: "AI-only one-shot with hosted agents",
          expectedOutcome: "Narration remains coherent for 90 minutes.",
          passCondition: "No agent loops or dead turns longer than 45 seconds.",
        },
      ],
    }),
  },
  {
    id: "ashen-crown",
    name: "Ashen Crown Academy",
    tagline: "Scholar blades, haunted dorms, and forbidden finals week.",
    genre: "Dark fantasy academy",
    mood: "Gothic, dramatic, conspiratorial",
    recommendedPartySize: "3-6 players",
    sessionLength: "90-150 min",
    viralityHooks: [
      "Term-based progression with season resets and school rankings.",
      "Players publish rival house NPCs for others to import.",
      "Duel highlights auto-clip around signature spell casts.",
    ],
    rules: {
      id: "sigil-d20",
      name: "Sigil d20",
      summary: "Roll d20 + trait. Overcasting grants power and adds Ruin.",
      turnLoop: ["Position", "Conjure", "Counter", "Reckoning"],
      failForwardPolicy: "Failures add Ruin clocks and spawn new omens.",
      escalationTrack: "Ruin 0-8 unlocks spectral events and boss phases.",
    },
    diceMoves: [
      {
        id: "ritual-cast",
        label: "Ritual Cast",
        expression: "1d20 + lore",
        successRule: "DC 13 normal, DC 17 forbidden spell.",
        failRule: "Spell resolves with Ruin +1.",
      },
      {
        id: "duel-clash",
        label: "Duel Clash",
        expression: "2d6 + poise",
        successRule: "10+ take initiative token.",
        failRule: "Opponent gains momentum.",
      },
      {
        id: "ward-break",
        label: "Ward Break",
        expression: "1d12 + will",
        successRule: "9+ break seal quietly.",
        failRule: "Seal shatters loudly and summons warden.",
      },
    ],
    archetypes: [
      {
        id: "ink-duelist",
        title: "Ink Duelist",
        fantasy: "Blade mage who writes temporary sigils in the air.",
        stats: [
          { key: "might", label: "Might", min: 0, max: 5, base: 2 },
          { key: "lore", label: "Lore", min: 0, max: 5, base: 2 },
          { key: "poise", label: "Poise", min: 0, max: 5, base: 3 },
        ],
        startingMoves: ["Counterstroke", "Sigil Step", "Ink Snare"],
        startingGear: ["Rune rapier", "Dorm crest", "Silver chalk"],
        generationPromptSeed: "Elegant frontline caster with duel-oriented timing.",
      },
      {
        id: "grave-scholar",
        title: "Grave Scholar",
        fantasy: "Archivist who bargains with ancestral memory.",
        stats: [
          { key: "might", label: "Might", min: 0, max: 5, base: 1 },
          { key: "lore", label: "Lore", min: 0, max: 5, base: 4 },
          { key: "poise", label: "Poise", min: 0, max: 5, base: 2 },
        ],
        startingMoves: ["Name the Dead", "Borrowed Thesis", "Waking Index"],
        startingGear: ["Bone folio", "Lantern key", "Warded ink"],
        generationPromptSeed: "Backline controller with investigative pressure.",
      },
      {
        id: "chapel-smuggler",
        title: "Chapel Smuggler",
        fantasy: "Contraband expert crossing sanctified checkpoints.",
        stats: [
          { key: "might", label: "Might", min: 0, max: 5, base: 2 },
          { key: "lore", label: "Lore", min: 0, max: 5, base: 1 },
          { key: "poise", label: "Poise", min: 0, max: 5, base: 4 },
        ],
        startingMoves: ["Hidden Pocket Realm", "Bell-Tower Route", "Clean Hands"],
        startingGear: ["Relic satchel", "Silent boots", "Smuggler seal"],
        generationPromptSeed: "Mobility + social deception specialist.",
      },
    ],
    hostedAgents: [
      {
        id: "gm-rector-aureline",
        role: "gm",
        name: "Rector Aureline",
        voice: "Regal with sharp sarcasm",
        personality: ["theatrical", "strict", "secretly empathetic"],
        directives: [
          "Frame consequences as academic reputation shifts.",
          "Offer knowledge tradeoffs against immediate power.",
          "Push duels toward character-defining dialogue.",
        ],
      },
      {
        id: "npc-house-warden",
        role: "npc",
        name: "Warden Brim",
        voice: "Gravelly and ceremonial",
        personality: ["duty-bound", "superstitious", "unyielding"],
        directives: ["Test intruders", "Protect restricted wing", "Hint at hidden patron"],
      },
    ],
    playerAgentTemplates: [
      {
        id: "agent-sable",
        role: "player",
        name: "Sable Quill",
        voice: "Poetic and restrained",
        personality: ["intense", "curious", "melancholic"],
        directives: ["Document omens", "Prioritize allies", "Risk Ruin for truth"],
      },
      {
        id: "agent-rime",
        role: "player",
        name: "Rime Bell",
        voice: "Blunt and practical",
        personality: ["protective", "skeptical", "stubborn"],
        directives: ["Control chokepoints", "Challenge authority", "Prevent collateral damage"],
      },
    ],
    maps: [
      {
        id: "obsidian-quad",
        name: "Obsidian Quad",
        biome: "Central academy courtyard under ashfall",
        camera: "isometric",
        lightingPreset: "Moonlit stone with ember glow",
        ambience: ["bell chimes", "wind through gargoyles", "distant chanting"],
        objectives: ["Win honor duel", "Protect first-years", "Decode herald mural"],
      },
      {
        id: "forbidden-stacks",
        name: "Forbidden Stacks",
        biome: "Vertical archive maze with moving shelves",
        camera: "topdown",
        lightingPreset: "Lantern pools + deep shadow wells",
        ambience: ["page rustle", "spectral whisper", "iron rail creak"],
        objectives: ["Find sealed codex", "Avoid watcher spirits", "Map hidden study routes"],
      },
      {
        id: "cathedral-bridge",
        name: "Cathedral Bridge",
        biome: "Wind-lashed skybridge above chapel abyss",
        camera: "cinematic",
        lightingPreset: "Storm flashes and candle islands",
        ambience: ["thunder", "stone groan", "choral undertone"],
        objectives: ["Break rival ward", "Recover stolen thesis", "Survive bridge collapse"],
      },
    ],
    dungeons: [
      {
        id: "crypt-of-midterms",
        name: "Crypt of Midterms",
        objective: "Pass the trial and recover the Dusk Thesis.",
        rooms: [
          {
            id: "hall-of-surnames",
            name: "Hall of Surnames",
            challenge: "Ancestral portraits demand true lineage answers.",
            checks: ["Ritual Cast DC 14", "Duel Clash 9+"],
            failForward: "Wrong answer summons a helpful but noisy ghost.",
            rewards: ["Lineage seal", "Shortcut to index chamber"],
          },
          {
            id: "inkwell-pit",
            name: "Inkwell Pit",
            challenge: "Living ink constructs rewrite movement paths.",
            checks: ["Ward Break 10+", "Ritual Cast DC 15"],
            failForward: "Path collapses but reveals contraband tunnel.",
            rewards: ["Contraband cache", "Ruin reduction charm"],
          },
          {
            id: "thesis-sanctum",
            name: "Thesis Sanctum",
            challenge: "Sentient thesis asks moral paradox questions mid-combat.",
            checks: ["Duel Clash 10+", "Ritual Cast DC 17"],
            failForward: "Thesis bonds unwillingly, adding cursed objective.",
            rewards: ["Dusk Thesis", "House prestige"],
          },
        ],
      },
    ],
    campaign: [
      {
        id: "arc-fall-term",
        title: "Fall Term of Broken Oaths",
        levelRange: "1-5",
        beats: [
          {
            id: "beat-1",
            title: "Initiation Ashfall",
            objective: "Survive ceremony sabotage and keep your house intact.",
            successOutcome: "House gets first claim on forbidden stacks access.",
            failForward: "House is blamed and must clear its name.",
            gmPrompt: "Tie social reputation and tactical outcomes together.",
          },
          {
            id: "beat-2",
            title: "Night of Sealed Bells",
            objective: "Stop chapel bells from summoning ruin storms.",
            successOutcome: "Campus calms and factions open negotiations.",
            failForward: "Storm lands; next sessions use hazard rules.",
            gmPrompt: "Let players trade personal secrets for mechanical bonuses.",
          },
          {
            id: "beat-3",
            title: "Finals at Dawn",
            objective: "Defeat rival pact and rewrite academy law.",
            successOutcome: "New school order and season two hooks.",
            failForward: "Old order persists; players become outlaws.",
            gmPrompt: "Close with one duel and one public speech scene.",
          },
        ],
      },
    ],
    creationKit: buildWorldCreationKit({
      worldName: "Ashen Crown Academy",
      genre: "Dark fantasy academy",
      mood: "Gothic and dramatic",
      uniqueConstraint: "Overcasting always resolves but adds Ruin clocks.",
      assetManifest: {
        tilesets: ["Gothic Hallways", "Arcane Classrooms", "Skybridge Ruins"],
        minis: ["House Duelists", "Spectral Wardens", "Scholars Pack"],
        props: ["Rune desks", "Candle walls", "Fallen bells"],
        music: ["ashen-hall.ogg", "duel-nocturne.ogg", "storm-final.ogg"],
        sfx: ["bell-strike.wav", "quill-scratch.wav", "ward-shatter.wav"],
      },
      sessionZeroChecklist: [
        "Set boundaries for horror tone and body-horror content.",
        "Assign house alliances and rivalries.",
        "Choose one forbidden topic each character is tempted by.",
      ],
      playtestMatrix: [
        {
          scenario: "Full social session with no combat",
          expectedOutcome: "Progress still moves campaign beat forward.",
          passCondition: "At least one reputation shift and one clue unlock occur.",
        },
        {
          scenario: "High-Ruin combat finale",
          expectedOutcome: "Ruin modifiers intensify play without stalling turns.",
          passCondition: "Turn pacing stays under 2 minutes per actor.",
        },
      ],
    }),
  },
  {
    id: "sunken-choir",
    name: "Sunken Choir of Nacre",
    tagline: "Dive temples of living coral and bargain with storm oracles.",
    genre: "Mythic ocean science-fantasy",
    mood: "Mystical, perilous, awe-heavy",
    recommendedPartySize: "2-5 players",
    sessionLength: "60-120 min",
    viralityHooks: [
      "Expedition seeds are shareable as one-click challenge runs.",
      "Biome remixes let creators fork maps and publish variants.",
      "Dynamic tides alter routes each week for replayability.",
    ],
    rules: {
      id: "tide-pool",
      name: "Tide Pool System",
      summary: "Roll pools of d6. 5-6 are successes; tides modify required successes.",
      turnLoop: ["Read Tide", "Act", "Adapt", "Resurface"],
      failForwardPolicy: "Low-success results create pressure clocks and resource drain.",
      escalationTrack: "Pressure 0-6 shifts oxygen, visibility, and hostility.",
    },
    diceMoves: [
      {
        id: "expedition-check",
        label: "Expedition Check",
        expression: "Xd6 (stat as dice count)",
        successRule: "Each 5-6 = 1 success; meet target successes.",
        failRule: "Miss by 1 grants partial progress and Pressure +1.",
      },
      {
        id: "current-dodge",
        label: "Current Dodge",
        expression: "4d6 baseline",
        successRule: "2+ successes avoid hazard fully.",
        failRule: "Take drift and separate from formation.",
      },
      {
        id: "oracle-parley",
        label: "Oracle Parley",
        expression: "3d6 + resonance die",
        successRule: "3+ successes reveal true prophecy thread.",
        failRule: "Oracle speaks in costly riddles.",
      },
    ],
    archetypes: [
      {
        id: "reef-striker",
        title: "Reef Striker",
        fantasy: "Frontline diver with harpoon propulsion and shield fins.",
        stats: [
          { key: "brawn", label: "Brawn", min: 1, max: 6, base: 4 },
          { key: "focus", label: "Focus", min: 1, max: 6, base: 2 },
          { key: "resonance", label: "Resonance", min: 1, max: 6, base: 2 },
        ],
        startingMoves: ["Jet Lunge", "Coral Guard", "Anchor Throw"],
        startingGear: ["Harpoon gauntlet", "Pressure mantle", "Reef beacon"],
        generationPromptSeed: "Durable diver that controls space and protects team.",
      },
      {
        id: "echo-cartographer",
        title: "Echo Cartographer",
        fantasy: "Maps hidden currents and reveals impossible routes.",
        stats: [
          { key: "brawn", label: "Brawn", min: 1, max: 6, base: 2 },
          { key: "focus", label: "Focus", min: 1, max: 6, base: 4 },
          { key: "resonance", label: "Resonance", min: 1, max: 6, base: 2 },
        ],
        startingMoves: ["Current Read", "Depth Echo", "Route Fold"],
        startingGear: ["Sonar slate", "Threadline spool", "Pressure compass"],
        generationPromptSeed: "Navigation + puzzle specialist for expedition pacing.",
      },
      {
        id: "choir-medium",
        title: "Choir Medium",
        fantasy: "Channels oracle harmonics to alter weather and intent.",
        stats: [
          { key: "brawn", label: "Brawn", min: 1, max: 6, base: 1 },
          { key: "focus", label: "Focus", min: 1, max: 6, base: 3 },
          { key: "resonance", label: "Resonance", min: 1, max: 6, base: 4 },
        ],
        startingMoves: ["Storm Canticle", "Quiet Reef", "Debt of Rain"],
        startingGear: ["Choir mask", "Oracle reed", "Salt script"],
        generationPromptSeed: "Support caster with social leverage over factions.",
      },
    ],
    hostedAgents: [
      {
        id: "gm-nacre-oracle",
        role: "gm",
        name: "Nacre Oracle",
        voice: "Warm, enigmatic, precise",
        personality: ["mythic", "patient", "eerie"],
        directives: [
          "Translate mechanics into sensory underwater narration.",
          "Offer one mystery clue for every major cost paid.",
          "Keep pressure high without removing player agency.",
        ],
      },
      {
        id: "npc-tide-warden",
        role: "npc",
        name: "Tide Warden Pel",
        voice: "Firm, measured",
        personality: ["guarded", "honorable", "traumatized"],
        directives: ["Demand proof of intent", "Protect shrine routes", "Challenge easy solutions"],
      },
    ],
    playerAgentTemplates: [
      {
        id: "agent-brine",
        role: "player",
        name: "Brine Fox",
        voice: "Dry humor, calm cadence",
        personality: ["curious", "nimble", "restless"],
        directives: ["Push exploration", "Tag hidden routes", "Avoid unnecessary battles"],
      },
      {
        id: "agent-keel",
        role: "player",
        name: "Keelwake",
        voice: "Steady and reassuring",
        personality: ["protective", "stoic", "resolute"],
        directives: ["Guard weaker allies", "Manage pressure clock", "Trade safety for intel when needed"],
      },
    ],
    maps: [
      {
        id: "glass-reef",
        name: "Glass Reef Expanse",
        biome: "Bioluminescent coral plains",
        camera: "isometric",
        lightingPreset: "Blue glow bloom with particle fog",
        ambience: ["whale chorus", "soft current rush", "distant metal creak"],
        objectives: ["Recover beacon", "Avoid razor shoals", "Mark safe resurfacing point"],
      },
      {
        id: "choir-trench",
        name: "Choir Trench",
        biome: "Vertical abyss with singing vents",
        camera: "cinematic",
        lightingPreset: "Minimal light cones with strobe plankton",
        ambience: ["low harmonic drones", "pressure rumbles", "echo pings"],
        objectives: ["Decode vent harmonics", "Shut down predator lure", "Escort relic carrier"],
      },
      {
        id: "storm-cistern",
        name: "Storm Cistern",
        biome: "Half-flooded sky temple reservoir",
        camera: "topdown",
        lightingPreset: "Lightning reflections + rain sheets",
        ambience: ["thunder", "sheet rain", "stone spillways"],
        objectives: ["Stabilize tide engine", "Negotiate oracle terms", "Escape collapsing aqueduct"],
      },
    ],
    dungeons: [
      {
        id: "abyssal-pipe",
        name: "Abyssal Pipe",
        objective: "Seal the leak feeding leviathan eggs.",
        rooms: [
          {
            id: "intake-gate",
            name: "Intake Gate",
            challenge: "Broken turbines force timed movement windows.",
            checks: ["Expedition Check target 3", "Current Dodge 2+ successes"],
            failForward: "You pass with oxygen loss and split inventory.",
            rewards: ["Pressure seal kit", "Shortcut to brood chamber"],
          },
          {
            id: "brood-chamber",
            name: "Brood Chamber",
            challenge: "Leviathan eggs react to vibration and light.",
            checks: ["Expedition Check target 4", "Oracle Parley 3+ successes"],
            failForward: "One egg hatches as a controllable companion threat.",
            rewards: ["Leviathan scale", "Faction leverage"],
          },
          {
            id: "final-lock",
            name: "Final Lock",
            challenge: "Manual pressure wheel while under attack.",
            checks: ["Current Dodge 2+ successes", "Expedition Check target 4"],
            failForward: "Seal holds briefly; forces sequel hook escape.",
            rewards: ["Temple pardon", "Storm-key fragment"],
          },
        ],
      },
    ],
    campaign: [
      {
        id: "arc-salt-oath",
        title: "Salt Oath Expedition",
        levelRange: "1-4",
        beats: [
          {
            id: "beat-1",
            title: "Broken Beacon",
            objective: "Restore lighthouse beacon swallowed by reef storm.",
            successOutcome: "Shipping lanes reopen and allies arrive.",
            failForward: "Beacon flickers, enabling pirate interception arc.",
            gmPrompt: "Reward navigation creativity as much as combat wins.",
          },
          {
            id: "beat-2",
            title: "Choir Debt",
            objective: "Repay or defy oracle bargain for storm passage.",
            successOutcome: "Oracle grants true map to trench heart.",
            failForward: "False map route adds hazard-heavy detour.",
            gmPrompt: "Keep moral stakes explicit: power, mercy, memory.",
          },
          {
            id: "beat-3",
            title: "Leviathan Wake",
            objective: "Close abyss breach before migration collapse.",
            successOutcome: "Region survives and new season opens sky routes.",
            failForward: "Breach narrows but releases roaming world boss.",
            gmPrompt: "Finish with a panoramic cinematic narration beat.",
          },
        ],
      },
    ],
    creationKit: buildWorldCreationKit({
      worldName: "Sunken Choir of Nacre",
      genre: "Mythic ocean science-fantasy",
      mood: "Mystical and perilous",
      uniqueConstraint: "Pressure clocks always advance during extended conflict scenes.",
      assetManifest: {
        tilesets: ["Coral Cathedral", "Abyss Trench", "Storm Reservoir"],
        minis: ["Dive Crew", "Leviathan Hatchlings", "Oracle Envoys"],
        props: ["Pressure valves", "Signal beacons", "Coral doors"],
        music: ["deep-glass.ogg", "oracle-choir.ogg", "storm-release.ogg"],
        sfx: ["sonar-ping.wav", "pressure-crack.wav", "water-rush.wav"],
      },
      sessionZeroChecklist: [
        "Set comfort levels for claustrophobia and deep-water tension.",
        "Choose expedition motive shared by all players.",
        "Define one personal debt to an ocean faction.",
      ],
      playtestMatrix: [
        {
          scenario: "Low-combat exploration run",
          expectedOutcome: "Navigation and oracle play remain satisfying.",
          passCondition: "At least two meaningful choices per scene.",
        },
        {
          scenario: "Boss encounter at Pressure 5+",
          expectedOutcome: "System remains readable under high modifiers.",
          passCondition: "No repeated rule lookups required by players.",
        },
      ],
    }),
  },
];

export function getWorldById(worldId: string): PlayableWorld | undefined {
  return playableWorlds.find((world) => world.id === worldId);
}
