export const storyAssets = [
  "lunchtable/story/story-1-1.png",
  "lunchtable/story/story-1-2.png",
  "lunchtable/story/story-1-3.png",
  "lunchtable/story/story-1-4.png",
  "lunchtable/story/story-2-1.png",
  "lunchtable/story/story-2-2.png",
  "lunchtable/story/story-2-3.png",
  "lunchtable/story/story-2-4.png",
  "lunchtable/story/story-3-1.png",
  "lunchtable/story/story-3-2.png",
  "lunchtable/story/story-3-3.png",
  "lunchtable/story/story-3-4.png",
  "lunchtable/story/story-4-1.png",
  "lunchtable/story/story-4-2.png",
  "lunchtable/story/story-4-3.png",
  "lunchtable/story/story-4-4.png",
] as const;

export const viceAssets = [
  "lunchtable/vices/adderall.png",
  "lunchtable/vices/alcohol.png",
  "lunchtable/vices/conspiracy.png",
  "lunchtable/vices/crypto.png",
  "lunchtable/vices/gambling.png",
  "lunchtable/vices/mlm.png",
  "lunchtable/vices/narcissism.png",
  "lunchtable/vices/rage.png",
  "lunchtable/vices/social-media.png",
  "lunchtable/vices/validation.png",
  "comic/vice-counter-2k.png",
  "lunchtable/vices/vice-splash.png",
] as const;

export const aboutAssets = [
  "lunchtable/about/about-1-concept.png",
  "lunchtable/about/about-2-cards.png",
  "lunchtable/about/about-3-stream.png",
  "lunchtable/about/about-4-platform.png",
] as const;

export const stageAssets = [
  "lunchtable/stages/stage-1-1-1.png",
  "lunchtable/stages/stage-1-1-2.png",
  "lunchtable/stages/stage-1-1-3.png",
] as const;

export const rootHeroAssets = [
  "lunchtable/landing-bg.jpg",
  "lunchtable/story-bg.png",
  "lunchtable/stream-bg.png",
  "lunchtable/watch-bg.png",
  "lunchtable/collection-bg.png",
  "lunchtable/privacy-bg.png",
  "comic/stagesbg-2k.png",
  "lunchtable/deck-bg.png",
  "lunchtable/menu-texture.png",
  "lunchtable/crumpled-paper.png",
  "lunchtable/firstday.png",
  "lunchtable/homework.png",
  "lunchtable/questions.png",
  "comic/retro-tv-2k.png",
  "lunchtable/ink-frame.png",
  "lunchtable/stream-overlay.png",
  "lunchtable/title.png",
  "lunchtable/logo.png",
  "lunchtable/music-button.png",
  "comic/music-1600.png",
  "lunchtable/milaidy.png",
  "lunchtable/milunchlady-classic.png",
  "lunchtable/milunchlady-cyber.png",
  "lunchtable/milunchlady-gamer.png",
  "lunchtable/milunchlady-goth.png",
  "lunchtable/milunchlady-hypebeast.png",
  "lunchtable/milunchlady-prep.png",
  "lunchtable/milunchladypfp.png",
  "lunchtable/milunchlaidypfp.png",
  "lunchtable/milunchlaidypfp2.png",
  "lunchtable/openclawdpfp.png",
  "lunchtable/openclawdpfp2.png",
  "lunchtable/platform-milaidy.png",
  "lunchtable/platform-openclawd.png",
  "lunchtable/deco-pills.png",
  "lunchtable/deco-shield.png",
] as const;

export const signupAvatarAssets = [
  "lunchtable/avatars/signup/avatar-001.png",
  "lunchtable/avatars/signup/avatar-002.png",
  "lunchtable/avatars/signup/avatar-003.png",
  "lunchtable/avatars/signup/avatar-004.png",
  "lunchtable/avatars/signup/avatar-005.png",
  "lunchtable/avatars/signup/avatar-006.png",
  "lunchtable/avatars/signup/avatar-007.png",
  "lunchtable/avatars/signup/avatar-008.png",
  "lunchtable/avatars/signup/avatar-009.png",
  "lunchtable/avatars/signup/avatar-010.png",
  "lunchtable/avatars/signup/avatar-011.png",
  "lunchtable/avatars/signup/avatar-012.png",
  "lunchtable/avatars/signup/avatar-013.png",
  "lunchtable/avatars/signup/avatar-014.png",
  "lunchtable/avatars/signup/avatar-015.png",
  "lunchtable/avatars/signup/avatar-016.png",
  "lunchtable/avatars/signup/avatar-017.png",
  "lunchtable/avatars/signup/avatar-018.png",
  "lunchtable/avatars/signup/avatar-019.png",
  "lunchtable/avatars/signup/avatar-020.png",
  "lunchtable/avatars/signup/avatar-021.png",
  "lunchtable/avatars/signup/avatar-022.png",
  "lunchtable/avatars/signup/avatar-023.png",
  "lunchtable/avatars/signup/avatar-024.png",
  "lunchtable/avatars/signup/avatar-025.png",
  "lunchtable/avatars/signup/avatar-026.png",
  "lunchtable/avatars/signup/avatar-027.png",
  "lunchtable/avatars/signup/avatar-028.png",
  "lunchtable/avatars/signup/avatar-029.png",
] as const;

export const hookCharacterAssets = [
  "lunchtable/milunchlady-classic.png",
  "lunchtable/milunchlady-cyber.png",
  "lunchtable/milunchlady-gamer.png",
  "lunchtable/milunchlady-goth.png",
  "lunchtable/milunchlady-hypebeast.png",
  "lunchtable/milunchlady-prep.png",
  "lunchtable/milunchladypfp.png",
  "lunchtable/openclawdpfp.png",
  "lunchtable/openclawdpfp2.png",
  "lunchtable/platform-milaidy.png",
  "lunchtable/platform-openclawd.png",
] as const;

export const backgroundCycleAssets = [
  "lunchtable/landing-bg.jpg",
  "lunchtable/collection-bg.png",
  "lunchtable/story-bg.png",
  "lunchtable/watch-bg.png",
  "lunchtable/stream-bg.png",
  "lunchtable/privacy-bg.png",
  "comic/stagesbg-2k.png",
  "lunchtable/deck-bg.png",
] as const;

export const castPanelAssets = [
  ...aboutAssets,
  "lunchtable/firstday.png",
  "lunchtable/homework.png",
  "lunchtable/questions.png",
  "comic/retro-tv-2k.png",
  "lunchtable/milaidy.png",
  "lunchtable/platform-milaidy.png",
  "lunchtable/platform-openclawd.png",
  "lunchtable/milunchlady-classic.png",
  "lunchtable/milunchlady-cyber.png",
  "lunchtable/milunchlady-gamer.png",
  "lunchtable/milunchlady-goth.png",
  "lunchtable/milunchlady-hypebeast.png",
  "lunchtable/milunchlady-prep.png",
  "lunchtable/openclawdpfp.png",
  "lunchtable/openclawdpfp2.png",
  "lunchtable/music-button.png",
  "comic/music-1600.png",
  "lunchtable/stream-overlay.png",
] as const;
